### ISSUE TITLE
Linux Import Images and PDFs

### ISSUE THREAD

**Issue by 4iMh9CawHdyu** [styluslabs/Write#1]
**In Linux** **Can't import images or documents into the one I'm working on.** **It says Error Reading:'displays address of the image'**
Thank You.

P.D. Best handwriting notes app IMO.

**Comment by pbsurf** [comment]
This should be fixed in the most recent release at styluslabs.com/download

**Comment by Atemu** [comment]
What's the version number? I tried http://www.styluslabs.com/write/write301.tar.gz but that 404s.
