### ISSUE TITLE
[RFE] Distro SDL2

### ISSUE THREAD

**Issue by lukts30** [styluslabs/Write#2]
Would you be inclined to accept a PR that adds support for building on Linux with the distro provided SDL2? 
A make flag that adds a `USE_SYSTEM_SDL` or something like that? 

Having this upstream in this repo would allow us (nixpkgs) to drop a [downstream patch](https://github.com/NixOS/nixpkgs/pull/346463/files#diff-f9c03f3f872b60ac7e4e3ae028ccf5bb12557e02f17cbf25608eeec924fbf635).

**Comment by pbsurf** [comment]
Sure!
