### ISSUE TITLE
Is version 300 AGPL?

### ISSUE THREAD

**Issue by Atemu** [styluslabs/Write#5]
Hi next to the new source port we still have the old binary packaged in Nixpkgs too (http://www.styluslabs.com/write/write300.tar.gz).

It's currently still listed as unfree but you've since relicensed to AGPL. My question is whether this binary is still unfree or whether it's derived from the AGPL code.

**Comment by pbsurf** [comment]
Yes, all past versions can now be considered AGPL.

**Comment by Atemu** [comment]
Well, that is only really true if one can access the source code ;)

That's why I'm specifically asking whether what is published here is indeed the exact source code version it's derived from.

**Comment by Atemu** [comment]
Friendly ping.

Does the published source code correspond with this artifact?

**Comment by pbsurf** [comment]
The git rev for any build is available in Preferences -> About.  If there is some concern about the old binary version, it should just be removed in favor of the newer build from source.

**Comment by Atemu** [comment]
That's probably fair. We have both in Nixpkgs right now but, given that the from-source port works just fine, we can probably just drop the binary package.

Thanks for open sourcing btw :)
