### ISSUE TITLE
HTML ... also PDF implementation...

### ISSUE THREAD

**Issue by 4iMh9CawHdyu** [styluslabs/Write#6]
Hello. A previous issue about images has been fixed in the new version for Linux. **Thank You Very Much**
On the other hand, in Linux. I've **been trying to import an html document. Can't do it, marks error.**
Also, would it be **possible to implement opening pdfs in Write?** that would be very nice and useful.

**Much Appreciated. Great program.**

**Comment by pbsurf** [comment]
HTML import is not supported.  For PDF, try this script: https://github.com/styluslabs/templates/blob/master/pdf2write.sh

**Comment by 4iMh9CawHdyu** [comment]
Hmmm. Was thinking more like Xournal where you just load the pdf into the
program no need for conversion.... but anyway, many thanks, assuming this
is the only way to do it currently..... much appreciated.

**Comment by Evidlo** [comment]
I was also interested in this.  I think this feature being built-in to Writer would be in high demand, as much of academic work is annotating papers (always in PDF format).
